### PR TITLE
1 add clippy to GitHub workflows

### LINKED ISSUE #1: Add clippy to github workflows
All pull requests should have to pass a check by clippy before being allowed to merge.

### PR DESCRIPTION
**Pull request by gokullan**
This PR addresses Issue #1. 

This is what I have done: I have added a file - `clippy-check.yml` inside the workflows directory. This is my first time doing workflows, so I just copy-pasted the content [here](https://github.com/actions-rs/clippy#with-stable-clippy) (I used `stable clippy`). Is this okay?

Testing: For testing purposes, I installed [act by nektos](https://github.com/nektos/act) locally in my forked repository. It gave me a lot of output in the terminal and I had a hard time interpreting what they meant. The final line said 'Job succeeded', so I thought it would work as expected.

Do let me know if something else is required. I will also read up more on using GitHub workflows in the meantime.

PS -  Ignore the first commit - I did that before reading the `CONTRIBUTING.md` doc.

### CODE REVIEW

**Review by Nate1729 — DISMISSED** [review]
It seems that your fork is behind. You should update your fork so that both `main` branches are in-sync.

Please add this clippy workflow as a job in the `main.yml` workflow.

Thanks for contributing!

**Comment by gokullan** [comment]
Hey, @Nate1729. I have updated my fork. A small question -`main.yml` has jobs that run on `push` events. Adding the clippy job to this file would cause all jobs to run on both `push` and `pull_request` events. Is that okay? Or do I need to use conditionals for each job?

**Comment by Nate1729** [comment]
> Hey, @Nate1729. I have updated my fork. A small question -`main.yml` has jobs that run on `push` events. Adding the clippy job to this file would cause all jobs to run on both `push` and `pull_request` events. Is that okay? Or do I need to use conditionals for each job?

Can you just add the clippy job and not modify the events that cause the workflow to run?

So
```YAML
jobs:
  rustfmt:
    ...
  test:
    ...
  clippy:
    <your_code_here>
```

**Review by Nate1729 — APPROVED** [review]
Thank you for the contribution! I will merge since the protections required signed commits.

**Pull request merged**
